version: '3.8'
services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: consul agent -dev -client=0.0.0.0 -ui
    environment:
      - CONSUL_BIND_INTERFACE=eth0